# This file was generated by GoReleaser. DO NOT EDIT.
cask "runhug" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "b5a99b2ac7c25acf97559498dfd2e8830948763aa255572a7c75311eed7a6418"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_darwin_arm64"
      binary "runhug_0.2.1_darwin_arm64", target: "runhug"
    end
    on_intel do
      sha256 "2f1bbd85c0de64b5c6035e19234bff0bdedcf0ea457cf3dddfc0ccb301e44244"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_darwin_amd64"
      binary "runhug_0.2.1_darwin_amd64", target: "runhug"
    end
  end
  on_linux do
    on_arm do
      sha256 "99f1771da2794e546e17891f88d241c1955a9bde609faa4d55e14027f63f00a8"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_linux_arm64"
      binary "runhug_0.2.1_linux_arm64", target: "runhug"
    end
    on_intel do
      sha256 "a3d9a07fecbb28a26dc768c8f12766e706c1b05348d04d452eaaf0ab6a647d4f"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_linux_amd64"
      binary "runhug_0.2.1_linux_amd64", target: "runhug"
    end
  end

  name "runhug"
  desc "Find the best Hugging Face model. Deploy it in minutes. Run it for pennies."
  homepage "https://github.com/openhat-security/runhug"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required
end
