# This file was generated by GoReleaser. DO NOT EDIT.
cask "runhug" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "31bc299daf0e1327dd6bf14472d21ff315343b56661362c919abf1c803bf4c9f"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_darwin_arm64"
      binary "runhug_0.3.0_darwin_arm64", target: "runhug"
    end
    on_intel do
      sha256 "2250ab85d3d0bec009eab4f6075bfcad087530409c6f7e028a9aa86be9122ab4"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_darwin_amd64"
      binary "runhug_0.3.0_darwin_amd64", target: "runhug"
    end
  end
  on_linux do
    on_arm do
      sha256 "04988f3b6e1e07f5853caa73517e5a5ba1c4dc4a0c8fbfa078e63f74c2a9769b"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_linux_arm64"
      binary "runhug_0.3.0_linux_arm64", target: "runhug"
    end
    on_intel do
      sha256 "1eaba78314726da16421b1b1e2e5bd72995fc959c7f615fda0bbd6fe402265c5"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_linux_amd64"
      binary "runhug_0.3.0_linux_amd64", target: "runhug"
    end
  end

  name "runhug"
  desc "Find the best Hugging Face model. Deploy it in minutes. Run it for pennies."
  homepage "https://github.com/openhat-security/runhug"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
