# This file was generated by GoReleaser. DO NOT EDIT.
cask "runhug" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "e4f550646e3292fbcaf35022479c284ed18d58ac63259f78ce7f4677b3984def"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_darwin_arm64"
      binary "runhug_0.3.1_darwin_arm64", target: "runhug"
    end
    on_intel do
      sha256 "cba637a1becb86e57a85db0ea64f90edb7dc186ddeec542334c0779a27b592e3"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_darwin_amd64"
      binary "runhug_0.3.1_darwin_amd64", target: "runhug"
    end
  end
  on_linux do
    on_arm do
      sha256 "d4917c8e033d4862fee9d9b931f0c31ff772f74ccd50869d6db0988b095497e8"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_linux_arm64"
      binary "runhug_0.3.1_linux_arm64", target: "runhug"
    end
    on_intel do
      sha256 "f3e612f4e70d64ddcb8cf63769fd29a3e0277d91a60b9bb041fbc197854b94a0"
      url "https://github.com/openhat-security/runhug/releases/download/v#{version}/runhug_#{version}_linux_amd64"
      binary "runhug_0.3.1_linux_amd64", target: "runhug"
    end
  end

  name "runhug"
  desc "Find the best Hugging Face model. Deploy it in minutes. Run it for pennies."
  homepage "https://github.com/openhat-security/runhug"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
