# This file was generated by GoReleaser. DO NOT EDIT.
cask "truffles" do
  version "1.0.15"

  on_macos do
    on_arm do
      sha256 "896eae475217e55fcae322d9324f4efcbaaf263ef8ccbf274f056b8b3f15fa60"
      url "https://github.com/openhat-security/truffles/releases/download/v#{version}/truffles_#{version}_darwin_arm64"
      binary "truffles_1.0.15_darwin_arm64", target: "truffles"
    end
    on_intel do
      sha256 "e7592e9c5ac4628d5f46df05cf5ac3b3e9f522e60f9e5f5b88e1e30985b651df"
      url "https://github.com/openhat-security/truffles/releases/download/v#{version}/truffles_#{version}_darwin_amd64"
      binary "truffles_1.0.15_darwin_amd64", target: "truffles"
    end
  end
  on_linux do
    on_arm do
      sha256 "b562625f872a49ba5ab9e74952e84db64d1c0805fd1af54ba9a0183fa80319ff"
      url "https://github.com/openhat-security/truffles/releases/download/v#{version}/truffles_#{version}_linux_arm64"
      binary "truffles_1.0.15_linux_arm64", target: "truffles"
    end
    on_intel do
      sha256 "b00843332ca953984ebc920deb60f870cbbf43fe7f7644800af57565a6f2292b"
      url "https://github.com/openhat-security/truffles/releases/download/v#{version}/truffles_#{version}_linux_amd64"
      binary "truffles_1.0.15_linux_amd64", target: "truffles"
    end
  end

  name "truffles"
  desc "Find GitHub repositories at scale, then scan git history for leaked credentials with trufflehog."
  homepage "https://github.com/openhat-security/truffles"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
